---
title: "R Notebook"
author: nikolays
date: 11/30/20
output: html_notebook
---


```{r setup, include=FALSE}
library(stringr)
```


```{r}
get_metric <- function(pathname,pattern,metric) {
    text <- system(paste0(
        "grep --include \\*.yaml -R -F '",
        pattern,
        "' ",
        pathname), intern = TRUE)
    m <- str_match(text, paste0("/N_([0-9]*)/.+", pattern,"\\s*([0-9.+-e]*)"))
    data.frame(nodes=as.integer(m[,2]),metric=metric,value=as.numeric(m[,3]),stringsAsFactors=F)
}
get_metric2 <- function(pathname,pattern,metric) {
    text <- system(paste0(
        "grep --include HPCG-Benchmark\\* -R -F '",
        pattern,
        "' ",
        pathname), intern = TRUE)
    m <- str_match(text, paste0("/N_([0-9]*)/.+", pattern,"([0-9.+-e]*)"))
    data.frame(nodes=as.integer(m[,2]),metric=metric,value=as.numeric(m[,3]),stringsAsFactors=F)
}

pathname <- "/home/nikolays/xdmod_wsp/appker_ookami/ookami/data/appsout/hpcg/stampede2-skx/2020-11-30/intel_icc_impi"
df1 <- cbind(
    data.frame(config="Stampede2-SKX, intel-HPCG, icc, impi"),
    rbind(
        get_metric(pathname,"HPCG result is VALID with a GFLOP/s rating of:","HPCG, GFLOP/s"),
        get_metric(pathname,"Scaled residual mean:", "Scaled residual mean"),
        get_metric(pathname,"Departure for SpMV:", "Departure for SpMV"),
        get_metric(pathname,"Departure for MG:", "Departure for MG")
    )
)

pathname <- "/home/nikolays/xdmod_wsp/appker_ookami/ookami/data/appsout/hpcg/stampede2-skx/2020-11-30/org_icc_impi"
df2 <- cbind(
    data.frame(config="Stampede2-SKX, icc, impi"),
    rbind(
        get_metric2(pathname,"HPCG result is VALID with a GFLOP/s rating of=","HPCG, GFLOP/s"),
        get_metric2(pathname,"Scaled residual mean=", "Scaled residual mean"),
        get_metric2(pathname,"Departure for SpMV=", "Departure for SpMV"),
        get_metric2(pathname,"Departure for MG=", "Departure for MG")
    )
)

pathname <- "/home/nikolays/xdmod_wsp/appker_ookami/ookami/data/appsout/hpcg/2020-11-27/gcc_openmpi"
df3 <- cbind(
    data.frame(config="Ookami, gcc, openmpi"),
    rbind(
        get_metric2(pathname,"HPCG result is VALID with a GFLOP/s rating of=","HPCG, GFLOP/s"),
        get_metric2(pathname,"Scaled residual mean=", "Scaled residual mean"),
        get_metric2(pathname,"Departure for SpMV=", "Departure for SpMV"),
        get_metric2(pathname,"Departure for MG=", "Departure for MG")
    )
)

pathname <- "/home/nikolays/xdmod_wsp/appker_ookami/ookami/data/appsout/hpcg/2020-11-27/gcc_mvapich2"
df4 <- cbind(
    data.frame(config="Ookami, gcc, mvapich"),
    rbind(
        get_metric2(pathname,"HPCG result is VALID with a GFLOP/s rating of=","HPCG, GFLOP/s"),
        get_metric2(pathname,"Scaled residual mean=", "Scaled residual mean"),
        get_metric2(pathname,"Departure for SpMV=", "Departure for SpMV"),
        get_metric2(pathname,"Departure for MG=", "Departure for MG")
    )
)

pathname <- "/home/nikolays/xdmod_wsp/appker_ookami/ookami/data/appsout/hpcg/2020-12-04/hpe_ver_cray_openmpi"
df5 <- cbind(
    data.frame(config="Ookami, HPE-HPCG, cray, openmpi"),
    rbind(
        get_metric2(pathname,"HPCG result is VALID with a GFLOP/s rating of=","HPCG, GFLOP/s"),
        get_metric2(pathname,"Scaled residual mean=", "Scaled residual mean"),
        get_metric2(pathname,"Departure for SpMV=", "Departure for SpMV"),
        get_metric2(pathname,"Departure for MG=", "Departure for MG")
    )
)

hpcg <- rbind(df4,df3,df5,df2,df1)

save(hpcg,file = "/home/nikolays/xdmod_wsp/appker_ookami/ookami/hpcg/hpcg.Rdata")
```

